# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43549efb36ba28a153aa56b3ab5c7f5e1d9583ecee8b892c201cda4a942d6d782cc09808cae9ac88a1689eb4ee0fb1afd43f63a07548641245974b3aebde789a

test:
  secret_key_base: 88bf310bf656f0013bf31d1b1e6acedf8a6b1b03477e5325c791c2c727f81d85bc6ac7e98cf2a5ab91de4377f9708d9120047f909392b59488d075ca87173d35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
